'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClsUsuarioWeb", [Namespace]:="http://schemas.datacontract.org/2004/07/Web_service"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClsUsuarioWeb
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private passwordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usuarioField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.passwordField, value) <> true) Then
                    Me.passwordField = value
                    Me.RaisePropertyChanged("password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.usuarioField, value) <> true) Then
                    Me.usuarioField = value
                    Me.RaisePropertyChanged("usuario")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetData(ByVal request As ServiceReference1.GetDataRequest) As ServiceReference1.GetDataResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetDataAsync(ByVal request As ServiceReference1.GetDataRequest) As System.Threading.Tasks.Task(Of ServiceReference1.GetDataResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/validarLogin", ReplyAction:="http://tempuri.org/IService1/validarLoginResponse")>  _
        Function validarLogin(ByVal request As ServiceReference1.validarLoginRequest) As ServiceReference1.validarLoginResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/validarLogin", ReplyAction:="http://tempuri.org/IService1/validarLoginResponse")>  _
        Function validarLoginAsync(ByVal request As ServiceReference1.validarLoginRequest) As System.Threading.Tasks.Task(Of ServiceReference1.validarLoginResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getListaServidoresBD", ReplyAction:="http://tempuri.org/IService1/getListaServidoresBDResponse")>  _
        Function getListaServidoresBD(ByVal request As ServiceReference1.getListaServidoresBDRequest) As ServiceReference1.getListaServidoresBDResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getListaServidoresBD", ReplyAction:="http://tempuri.org/IService1/getListaServidoresBDResponse")>  _
        Function getListaServidoresBDAsync(ByVal request As ServiceReference1.getListaServidoresBDRequest) As System.Threading.Tasks.Task(Of ServiceReference1.getListaServidoresBDResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetData", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public value As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal value As Integer)
            MyBase.New
            Me.value = value
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetDataResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetDataResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDataResult As String)
            MyBase.New
            Me.GetDataResult = GetDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="validarLogin", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class validarLoginRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public usue As ServiceReference1.ClsUsuarioWeb
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usue As ServiceReference1.ClsUsuarioWeb)
            MyBase.New
            Me.usue = usue
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="validarLoginResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class validarLoginResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public validarLoginResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal validarLoginResult As Integer)
            MyBase.New
            Me.validarLoginResult = validarLoginResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getListaServidoresBD", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getListaServidoresBDRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getListaServidoresBDResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getListaServidoresBDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public getListaServidoresBDResult As System.Data.DataTable
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getListaServidoresBDResult As System.Data.DataTable)
            MyBase.New
            Me.getListaServidoresBDResult = getListaServidoresBDResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits ServiceReference1.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IService1)
        Implements ServiceReference1.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal request As ServiceReference1.GetDataRequest) As ServiceReference1.GetDataResponse Implements ServiceReference1.IService1.GetData
            Return MyBase.Channel.GetData(request)
        End Function
        
        Public Function GetDataAsync(ByVal request As ServiceReference1.GetDataRequest) As System.Threading.Tasks.Task(Of ServiceReference1.GetDataResponse) Implements ServiceReference1.IService1.GetDataAsync
            Return MyBase.Channel.GetDataAsync(request)
        End Function
        
        Public Function validarLogin(ByVal request As ServiceReference1.validarLoginRequest) As ServiceReference1.validarLoginResponse Implements ServiceReference1.IService1.validarLogin
            Return MyBase.Channel.validarLogin(request)
        End Function
        
        Public Function validarLoginAsync(ByVal request As ServiceReference1.validarLoginRequest) As System.Threading.Tasks.Task(Of ServiceReference1.validarLoginResponse) Implements ServiceReference1.IService1.validarLoginAsync
            Return MyBase.Channel.validarLoginAsync(request)
        End Function
        
        Public Function getListaServidoresBD(ByVal request As ServiceReference1.getListaServidoresBDRequest) As ServiceReference1.getListaServidoresBDResponse Implements ServiceReference1.IService1.getListaServidoresBD
            Return MyBase.Channel.getListaServidoresBD(request)
        End Function
        
        Public Function getListaServidoresBDAsync(ByVal request As ServiceReference1.getListaServidoresBDRequest) As System.Threading.Tasks.Task(Of ServiceReference1.getListaServidoresBDResponse) Implements ServiceReference1.IService1.getListaServidoresBDAsync
            Return MyBase.Channel.getListaServidoresBDAsync(request)
        End Function
    End Class
End Namespace
